services:

  postgres:
    image: postgres:17.7-alpine
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: booking
    ports:
     - 5433:5432
    labels:
      org.springframework.boot.service-connection: postgres